version: '3.7'
services:
    proxy:
        build: .\proxy\
        ports:
            - "8083:80"
        networks:
            internal_nw:
                ipv4_address: 172.28.0.2
    app:
        build: .\app\
        networks:
            internal_nw:
                ipv4_address: 172.28.0.3
networks:
    internal_nw:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
